name: Build and Publish Conda Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: Install mamba
      run: conda install mamba -c conda-forge -y
    - name: Install boa
      run: mamba install -y -c conda-forge boa

    - name: Build Conda Package with mamba
      run: conda mambabuild .

    - name: Publish Conda Package
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u ${{ secrets.ANACONDA_USERNAME }} -l main $CONDA_PREFIX/conda-bld/linux-64/tidecluster-*.tar.bz2
